function validate_dynare_runtime_opts(opts, n_sectors, context)
% VALIDATE_DYNARE_RUNTIME_OPTS Validate standardized Dynare runtime options

if nargin < 3 || isempty(context)
    context = 'validate_dynare_runtime_opts';
end

assert(isstruct(opts), ...
    'validate_dynare_runtime_opts:InvalidOpts', ...
    '[%s] opts must be a struct.', context);

validate_integer_scalar(opts.ir_horizon, 1, inf, context, 'ir_horizon');
validate_integer_scalar(opts.simul_T, 1, inf, context, 'simul_T');
validate_integer_scalar(opts.simul_burn_in, 0, inf, context, 'simul_burn_in');
validate_integer_scalar(opts.simul_burn_out, 0, inf, context, 'simul_burn_out');
validate_integer_scalar(opts.mit_lookahead_horizon, 3, inf, context, 'mit_lookahead_horizon');

if ~isempty(opts.rng_seed)
    validate_integer_scalar(opts.rng_seed, 0, inf, context, 'rng_seed');
end

assert(ischar(opts.model_type) || (isstring(opts.model_type) && isscalar(opts.model_type)), ...
    'validate_dynare_runtime_opts:InvalidModelType', ...
    '[%s] model_type must be a character vector or scalar string.', context);
model_type = char(opts.model_type);
valid_model_types = {'VA', 'GO', 'GO_noVA'};
assert(any(strcmp(model_type, valid_model_types)), ...
    'validate_dynare_runtime_opts:UnsupportedModelType', ...
    '[%s] Unsupported model_type ''%s''. Expected one of: %s.', ...
    context, model_type, strjoin(valid_model_types, ', '));

assert(ischar(opts.mit_solver_mode) || (isstring(opts.mit_solver_mode) && isscalar(opts.mit_solver_mode)), ...
    'validate_dynare_runtime_opts:InvalidMITSolverMode', ...
    '[%s] mit_solver_mode must be a character vector or scalar string.', context);
mit_solver_mode = char(opts.mit_solver_mode);
valid_mit_solver_modes = {'rolling', 'legacy'};
assert(any(strcmp(mit_solver_mode, valid_mit_solver_modes)), ...
    'validate_dynare_runtime_opts:UnsupportedMITSolverMode', ...
    '[%s] Unsupported mit_solver_mode ''%s''. Expected one of: %s.', ...
    context, mit_solver_mode, strjoin(valid_mit_solver_modes, ', '));

if isfield(opts, 'mit_pf_tolf')
    validate_positive_scalar(opts.mit_pf_tolf, context, 'mit_pf_tolf');
end

if isfield(opts, 'mit_rolling_horizon_mode')
    assert(ischar(opts.mit_rolling_horizon_mode) || ...
        (isstring(opts.mit_rolling_horizon_mode) && isscalar(opts.mit_rolling_horizon_mode)), ...
        'validate_dynare_runtime_opts:InvalidMITHorizonMode', ...
        '[%s] mit_rolling_horizon_mode must be a character vector or scalar string.', context);
    mit_rolling_horizon_mode = char(opts.mit_rolling_horizon_mode);
    valid_mit_rolling_horizon_modes = {'fixed', 'remaining', 'remaining_plus_terminal', 'remaining_plus_two_terminal'};
    assert(any(strcmp(mit_rolling_horizon_mode, valid_mit_rolling_horizon_modes)), ...
        'validate_dynare_runtime_opts:UnsupportedMITHorizonMode', ...
        '[%s] Unsupported mit_rolling_horizon_mode ''%s''. Expected one of: %s.', ...
        context, mit_rolling_horizon_mode, strjoin(valid_mit_rolling_horizon_modes, ', '));
end

validate_sector_indices(opts.sector_indices, n_sectors, context);

flag_names = {'run_firstorder_simul', 'run_secondorder_simul', 'run_firstorder_irs', ...
    'run_secondorder_irs', 'run_pf_irs', 'run_pf_simul', 'run_mit_shocks_simul', ...
    'continue_on_failure'};
for i = 1:numel(flag_names)
    field_name = flag_names{i};
    validate_logical_like_scalar(opts.(field_name), context, field_name);
end

if isfield(opts, 'mit_rolling_stop_after_active')
    validate_logical_like_scalar(opts.mit_rolling_stop_after_active, context, ...
        'mit_rolling_stop_after_active');
end
end

function validate_integer_scalar(value, min_value, max_value, context, field_name)
assert(isnumeric(value) && isscalar(value) && isfinite(value) && value == floor(value) && ...
    value >= min_value && value <= max_value, ...
    'validate_dynare_runtime_opts:InvalidIntegerScalar', ...
    '[%s] %s must be an integer scalar in [%g, %g].', context, field_name, min_value, max_value);
end

function validate_positive_scalar(value, context, field_name)
assert(isnumeric(value) && isscalar(value) && isfinite(value) && value > 0, ...
    'validate_dynare_runtime_opts:InvalidPositiveScalar', ...
    '[%s] %s must be a finite positive scalar.', context, field_name);
end

function validate_logical_like_scalar(value, context, field_name)
assert((islogical(value) || isnumeric(value)) && isscalar(value), ...
    'validate_dynare_runtime_opts:InvalidFlag', ...
    '[%s] %s must be a logical-like scalar.', context, field_name);
end
