function validate_ModelData_simulation(ModelData_simulation, flags, context)
% VALIDATE_MODELDATA_SIMULATION Validate the heavy simulation artifact

if nargin < 3
    context = 'validate_ModelData_simulation';
end

assert(isstruct(ModelData_simulation) && ~isempty(fieldnames(ModelData_simulation)), ...
    'validate_ModelData_simulation:InvalidArtifact', ...
    '[%s] ModelData_simulation must be a non-empty struct.', context);

assert_required_fields(ModelData_simulation, {'metadata'}, context, 'ModelData_simulation');
assert_required_fields(ModelData_simulation.metadata, ...
    {'save_label', 'exp_paths', 'run_flags', 'has_irfs'}, context, 'ModelData_simulation.metadata');
assert_run_flags_match(ModelData_simulation.metadata.run_flags, flags, context, 'ModelData_simulation.metadata.run_flags');

if isfield(ModelData_simulation, 'Shared') && isstruct(ModelData_simulation.Shared) && ...
        ~isempty(fieldnames(ModelData_simulation.Shared))
    validate_shared_views(ModelData_simulation.Shared, context);
end

simulation_blocks = {
    flags.has_1storder, 'FirstOrder';
    flags.has_2ndorder, 'SecondOrder';
    flags.has_pf, 'PerfectForesight';
    flags.has_mit, 'MITShocks';
};

for i = 1:size(simulation_blocks, 1)
    if ~simulation_blocks{i, 1}
        continue;
    end

    block_name = simulation_blocks{i, 2};
    block = assert_block_exists(ModelData_simulation, block_name, context);
    assert_required_fields(block, ...
        {'burnin_simul', 'shocks_simul', 'burnout_simul', 'variable_indices', ...
        'burn_in', 'burn_out', 'T_active', 'T_total', 'summary_stats'}, ...
        context, ['ModelData_simulation.' block_name]);
    idx = block.variable_indices;
    validate_variable_indices(idx, context, ['ModelData_simulation.' block_name '.variable_indices']);
    validate_simulation_block(block, block_name, idx, context);
    validate_summary_stats(block.summary_stats, block, block_name, idx, context);
    validate_optional_aggregate_series(block, context, block_name);
end

if flags.has_1storder || flags.has_2ndorder || flags.has_pf || flags.has_mit
    assert(isfield(ModelData_simulation, 'Shocks') && isstruct(ModelData_simulation.Shocks), ...
        'validate_ModelData_simulation:MissingShocks', ...
        '[%s] ModelData_simulation.Shocks must exist when any simulation ran.', context);
    assert_required_fields(ModelData_simulation.Shocks, ...
        {'data', 'T', 'rng_state', 'Sigma_A'}, context, 'ModelData_simulation.Shocks');
    validate_shocks_block(ModelData_simulation.Shocks, context);
end
end

function block = assert_block_exists(ModelData_simulation, block_name, context)
assert(isfield(ModelData_simulation, block_name), ...
    'validate_ModelData_simulation:MissingBlock', ...
    '[%s] Missing simulation block: %s', context, block_name);
block = ModelData_simulation.(block_name);
end

function validate_variable_indices(idx, context, idx_name)
assert(isstruct(idx), ...
    'validate_ModelData_simulation:InvalidIndices', ...
    '[%s] %s must be a struct.', context, idx_name);
assert_required_fields(idx, {'n', 'n_states', 'n_policies', 'n_dynare'}, context, idx_name);
assert(idx.n_dynare == idx.n_states + idx.n_policies, ...
    'validate_ModelData_simulation:InconsistentIndices', ...
    '[%s] %s must satisfy n_dynare = n_states + n_policies.', context, idx_name);
end

function validate_simulation_block(block, block_name, idx, context)
validate_window_matrix(block.burnin_simul, idx, context, block_name, 'burnin_simul');
validate_window_matrix(block.shocks_simul, idx, context, block_name, 'shocks_simul');
validate_window_matrix(block.burnout_simul, idx, context, block_name, 'burnout_simul');

assert(isnumeric(block.burn_in) && isscalar(block.burn_in) && block.burn_in >= 0, ...
    'validate_ModelData_simulation:InvalidBurnIn', ...
    '[%s] ModelData_simulation.%s.burn_in must be a non-negative scalar.', context, block_name);
assert(isnumeric(block.burn_out) && isscalar(block.burn_out) && block.burn_out >= 0, ...
    'validate_ModelData_simulation:InvalidBurnOut', ...
    '[%s] ModelData_simulation.%s.burn_out must be a non-negative scalar.', context, block_name);
assert(isnumeric(block.T_active) && isscalar(block.T_active) && block.T_active >= 1, ...
    'validate_ModelData_simulation:InvalidActiveHorizon', ...
    '[%s] ModelData_simulation.%s.T_active must be a positive scalar.', context, block_name);
assert(isnumeric(block.T_total) && isscalar(block.T_total) && block.T_total >= block.T_active, ...
    'validate_ModelData_simulation:InvalidTotalHorizon', ...
    '[%s] ModelData_simulation.%s.T_total must be at least T_active.', context, block_name);

assert(size(block.burnin_simul, 2) == block.burn_in, ...
    'validate_ModelData_simulation:BurnInMismatch', ...
    '[%s] ModelData_simulation.%s.burnin_simul columns must equal burn_in.', context, block_name);
assert(size(block.shocks_simul, 2) == block.T_active, ...
    'validate_ModelData_simulation:ActiveHorizonMismatch', ...
    '[%s] ModelData_simulation.%s.shocks_simul columns must equal T_active.', context, block_name);
assert(size(block.burnout_simul, 2) == block.burn_out, ...
    'validate_ModelData_simulation:BurnOutMismatch', ...
    '[%s] ModelData_simulation.%s.burnout_simul columns must equal burn_out.', context, block_name);

expected_total = block.burn_in + block.T_active + block.burn_out;
assert(block.T_total == expected_total, ...
    'validate_ModelData_simulation:TotalHorizonMismatch', ...
    '[%s] ModelData_simulation.%s.T_total must equal burn_in + T_active + burn_out.', ...
    context, block_name);

if strcmp(block_name, 'MITShocks')
    assert(block.burn_in == 0, ...
        'validate_ModelData_simulation:MITBurnInMismatch', ...
        '[%s] ModelData_simulation.MITShocks.burn_in must equal 0.', context);
end
end

function validate_window_matrix(window, idx, context, block_name, field_name)
assert(isnumeric(window) && ismatrix(window) && size(window, 1) == idx.n_dynare, ...
    'validate_ModelData_simulation:InvalidWindowSize', ...
    '[%s] ModelData_simulation.%s.%s must be a numeric matrix with %d rows.', ...
    context, block_name, field_name, idx.n_dynare);
end

function validate_summary_stats(summary_stats, block, block_name, idx, context)
assert(isstruct(summary_stats) && ~isempty(fieldnames(summary_stats)), ...
    'validate_ModelData_simulation:InvalidSummaryStats', ...
    '[%s] ModelData_simulation.%s.summary_stats must be a non-empty struct.', ...
    context, block_name);
assert_required_fields(summary_stats, {'sample_window', 'aggregate_definition', ...
    'burn_in', 'burn_out', 'T_active', 'T_total', 'states_mean', 'states_std', ...
    'policies_mean', 'policies_std', 'ModelStats'}, ...
    context, ['ModelData_simulation.' block_name '.summary_stats']);
assert(strcmp(summary_stats.sample_window, 'shocks_simul'), ...
    'validate_ModelData_simulation:InvalidSummaryWindow', ...
    '[%s] ModelData_simulation.%s.summary_stats.sample_window must equal shocks_simul.', ...
    context, block_name);
assert(ischar(summary_stats.aggregate_definition) || isstring(summary_stats.aggregate_definition), ...
    'validate_ModelData_simulation:InvalidAggregateDefinition', ...
    '[%s] ModelData_simulation.%s.summary_stats.aggregate_definition must be text.', ...
    context, block_name);
assert(isnumeric(summary_stats.states_mean) && isvector(summary_stats.states_mean) && ...
    numel(summary_stats.states_mean) == idx.n_states, ...
    'validate_ModelData_simulation:InvalidStatesMean', ...
    '[%s] ModelData_simulation.%s.summary_stats.states_mean must have length n_states.', ...
    context, block_name);
assert(isnumeric(summary_stats.states_std) && isvector(summary_stats.states_std) && ...
    numel(summary_stats.states_std) == idx.n_states, ...
    'validate_ModelData_simulation:InvalidStatesStd', ...
    '[%s] ModelData_simulation.%s.summary_stats.states_std must have length n_states.', ...
    context, block_name);
assert(isnumeric(summary_stats.policies_mean) && isvector(summary_stats.policies_mean) && ...
    numel(summary_stats.policies_mean) == idx.n_policies, ...
    'validate_ModelData_simulation:InvalidPoliciesMean', ...
    '[%s] ModelData_simulation.%s.summary_stats.policies_mean must have length n_policies.', ...
    context, block_name);
assert(isnumeric(summary_stats.policies_std) && isvector(summary_stats.policies_std) && ...
    numel(summary_stats.policies_std) == idx.n_policies, ...
    'validate_ModelData_simulation:InvalidPoliciesStd', ...
    '[%s] ModelData_simulation.%s.summary_stats.policies_std must have length n_policies.', ...
    context, block_name);
assert(isstruct(summary_stats.ModelStats) && ~isempty(fieldnames(summary_stats.ModelStats)), ...
    'validate_ModelData_simulation:InvalidModelStats', ...
    '[%s] ModelData_simulation.%s.summary_stats.ModelStats must be a non-empty struct.', ...
    context, block_name);
summary_fields = {'burn_in', 'burn_out', 'T_active', 'T_total'};
for i = 1:numel(summary_fields)
    field_name = summary_fields{i};
    assert(isnumeric(summary_stats.(field_name)) && isscalar(summary_stats.(field_name)), ...
        'validate_ModelData_simulation:InvalidSummaryHorizons', ...
        '[%s] ModelData_simulation.%s.summary_stats.%s must be a numeric scalar.', ...
        context, block_name, field_name);
    assert(isequal(summary_stats.(field_name), block.(field_name)), ...
        'validate_ModelData_simulation:SummaryHorizonMismatch', ...
        '[%s] ModelData_simulation.%s.summary_stats.%s must match the simulation block.', ...
        context, block_name, field_name);
end
end

function validate_shocks_block(Shocks, context)
assert(isnumeric(Shocks.data) && ismatrix(Shocks.data), ...
    'validate_ModelData_simulation:InvalidShockMatrix', ...
    '[%s] ModelData_simulation.Shocks.data must be a numeric matrix.', context);
assert(isnumeric(Shocks.T) && isscalar(Shocks.T) && Shocks.T == size(Shocks.data, 1), ...
    'validate_ModelData_simulation:InvalidShockHorizon', ...
    '[%s] ModelData_simulation.Shocks.T must match size(Shocks.data, 1).', context);
assert(isnumeric(Shocks.Sigma_A) && ismatrix(Shocks.Sigma_A) && ...
    size(Shocks.Sigma_A, 1) == size(Shocks.Sigma_A, 2), ...
    'validate_ModelData_simulation:InvalidShockCovariance', ...
    '[%s] ModelData_simulation.Shocks.Sigma_A must be square.', context);
assert(size(Shocks.data, 2) == size(Shocks.Sigma_A, 1), ...
    'validate_ModelData_simulation:ShockDimensionMismatch', ...
    '[%s] ModelData_simulation.Shocks.data columns must match size(Sigma_A, 1).', context);
assert(isstruct(Shocks.rng_state), ...
    'validate_ModelData_simulation:InvalidRngState', ...
    '[%s] ModelData_simulation.Shocks.rng_state must be a struct.', context);
end

function assert_run_flags_match(actual_flags, expected_flags, context, flags_name)
assert(isstruct(actual_flags), ...
    'validate_ModelData_simulation:InvalidRunFlags', ...
    '[%s] %s must be a struct.', context, flags_name);
assert_required_fields(actual_flags, {'has_1storder', 'has_2ndorder', 'has_pf', 'has_mit'}, context, flags_name);
expected_fields = fieldnames(expected_flags);
for i = 1:numel(expected_fields)
    field_name = expected_fields{i};
    assert(isfield(actual_flags, field_name) && isequal(actual_flags.(field_name), expected_flags.(field_name)), ...
        'validate_ModelData_simulation:RunFlagMismatch', ...
        '[%s] %s.%s does not match the requested runtime flags.', ...
        context, flags_name, field_name);
end
end

function assert_required_fields(s, required_fields, context, struct_name)
missing_fields = {};
for i = 1:numel(required_fields)
    if ~isfield(s, required_fields{i})
        missing_fields{end+1} = required_fields{i}; %#ok<AGROW>
    end
end

if ~isempty(missing_fields)
    error('validate_ModelData_simulation:MissingFields', ...
        '[%s] %s is missing required fields: %s', ...
        context, struct_name, strjoin(missing_fields, ', '));
end
end

function validate_shared_views(Shared, context)
if isfield(Shared, 'Solution')
    assert(isstruct(Shared.Solution) && ~isempty(fieldnames(Shared.Solution)), ...
        'validate_ModelData_simulation:InvalidSharedSolution', ...
        '[%s] ModelData_simulation.Shared.Solution must be a non-empty struct.', context);
    assert_required_fields(Shared.Solution, {'StateSpace', 'indices'}, context, ...
        'ModelData_simulation.Shared.Solution');
    assert_required_fields(Shared.Solution.StateSpace, {'A', 'B', 'C', 'D'}, context, ...
        'ModelData_simulation.Shared.Solution.StateSpace');
end

if isfield(Shared, 'Statistics')
    assert(isstruct(Shared.Statistics) && ~isempty(fieldnames(Shared.Statistics)), ...
        'validate_ModelData_simulation:InvalidSharedStatistics', ...
        '[%s] ModelData_simulation.Shared.Statistics must be a non-empty struct.', context);
    if isfield(Shared.Statistics, 'TheoStats')
        assert(isstruct(Shared.Statistics.TheoStats) && ~isempty(fieldnames(Shared.Statistics.TheoStats)), ...
            'validate_ModelData_simulation:InvalidSharedTheoStats', ...
            '[%s] ModelData_simulation.Shared.Statistics.TheoStats must be a non-empty struct.', context);
    end
    validate_optional_numeric_vector(Shared.Statistics, 'shocks_sd', context);
    validate_optional_numeric_vector(Shared.Statistics, 'states_sd', context);
    validate_optional_numeric_vector(Shared.Statistics, 'policies_sd', context);
end

if isfield(Shared, 'SteadyStateAggregates')
    assert(isstruct(Shared.SteadyStateAggregates) && ~isempty(fieldnames(Shared.SteadyStateAggregates)), ...
        'validate_ModelData_simulation:InvalidSharedSteadyStateAggregates', ...
        '[%s] ModelData_simulation.Shared.SteadyStateAggregates must be a non-empty struct.', context);
end
end

function validate_optional_numeric_vector(s, field_name, context)
if ~isfield(s, field_name)
    return;
end

assert(isnumeric(s.(field_name)) && isvector(s.(field_name)), ...
    'validate_ModelData_simulation:InvalidSharedStatistic', ...
    '[%s] ModelData_simulation.Shared.Statistics.%s must be a numeric vector.', ...
    context, field_name);
end

function validate_optional_aggregate_series(block, context, block_name)
if ~isfield(block, 'aggregate_series')
    return;
end

aggregate_series = block.aggregate_series;
assert(isstruct(aggregate_series) && ~isempty(fieldnames(aggregate_series)), ...
    'validate_ModelData_simulation:InvalidAggregateSeries', ...
    '[%s] ModelData_simulation.%s.aggregate_series must be a non-empty struct.', ...
    context, block_name);

required_aggregates = {'C', 'L', 'GDP', 'I', 'K', 'utility_intratemp'};
for i = 1:numel(required_aggregates)
    aggregate_name = required_aggregates{i};
    assert(isfield(aggregate_series, aggregate_name), ...
        'validate_ModelData_simulation:MissingAggregateSeries', ...
        '[%s] ModelData_simulation.%s.aggregate_series.%s is missing.', ...
        context, block_name, aggregate_name);

    series = aggregate_series.(aggregate_name);
    assert(isstruct(series), ...
        'validate_ModelData_simulation:InvalidAggregateSeriesWindow', ...
        '[%s] ModelData_simulation.%s.aggregate_series.%s must be a struct.', ...
        context, block_name, aggregate_name);
    assert_required_fields(series, {'burnin', 'active', 'burnout', 'full'}, context, ...
        sprintf('ModelData_simulation.%s.aggregate_series.%s', block_name, aggregate_name));
end
end
