function validate_ModelData_IRs(ModelData_IRs, context)
% VALIDATE_MODELDATA_IRS Validate the saved IRF artifact

if nargin < 2
    context = 'validate_ModelData_IRs';
end

assert(isstruct(ModelData_IRs) && ~isempty(fieldnames(ModelData_IRs)), ...
    'validate_ModelData_IRs:InvalidArtifact', ...
    '[%s] ModelData_IRs must be a non-empty struct.', context);

required_top = {'save_label', 'sector_indices', 'ir_horizon', 'shocks', 'metadata'};
assert_required_fields(ModelData_IRs, required_top, context, 'ModelData_IRs');
assert_required_fields(ModelData_IRs.metadata, {'run_flags', 'has_irfs'}, context, 'ModelData_IRs.metadata');
assert_required_fields(ModelData_IRs.metadata.run_flags, {'has_1storder', 'has_2ndorder', 'has_pf', 'has_mit'}, ...
    context, 'ModelData_IRs.metadata.run_flags');

n_shocks = numel(ModelData_IRs.shocks);
n_analyzed = numel(ModelData_IRs.sector_indices);
R = get_ir_row_map();
run_flags = ModelData_IRs.metadata.run_flags;

assert(ModelData_IRs.metadata.has_irfs == true, ...
    'validate_ModelData_IRs:InvalidMetadataFlag', ...
    '[%s] ModelData_IRs.metadata.has_irfs must be true.', context);

for i = 1:n_shocks
    shock_artifact = ModelData_IRs.shocks(i);
    assert_required_fields(shock_artifact, ...
        {'sector_indices', 'run_flags', 'metadata', 'entries', 'summary_stats'}, ...
        context, sprintf('ModelData_IRs.shocks(%d)', i));
    assert(isequal(shock_artifact.sector_indices(:), ModelData_IRs.sector_indices(:)), ...
        'validate_ModelData_IRs:ShockSectorMismatch', ...
        '[%s] ModelData_IRs.shocks(%d).sector_indices must match top-level sector_indices.', context, i);
    assert_required_fields(shock_artifact.run_flags, {'has_1storder', 'has_2ndorder', 'has_pf', 'has_mit'}, ...
        context, sprintf('ModelData_IRs.shocks(%d).run_flags', i));
    validate_summary_stats(shock_artifact.summary_stats, n_analyzed, context, ...
        sprintf('ModelData_IRs.shocks(%d).summary_stats', i));

    assert(isstruct(shock_artifact.entries) && numel(shock_artifact.entries) == n_analyzed, ...
        'validate_ModelData_IRs:InvalidShockEntryCount', ...
        '[%s] ModelData_IRs.shocks(%d).entries must contain one struct per analyzed sector.', context, i);

    for j = 1:n_analyzed
        shock_entry = shock_artifact.entries(j);
        assert_required_fields(shock_entry, {'sector_idx', 'client_idx', 'first_order', 'second_order', ...
            'perfect_foresight'}, context, sprintf('ModelData_IRs.shocks(%d).entries(%d)', i, j));
        assert(shock_entry.sector_idx == ModelData_IRs.sector_indices(j), ...
            'validate_ModelData_IRs:ShockEntrySectorMismatch', ...
            '[%s] Shock artifact entry sector_idx does not match ModelData_IRs.sector_indices.', context);

        validate_irf_matrix(shock_entry.first_order, R.N_ROWS, logical(run_flags.has_1storder), ...
            context, sprintf('ModelData_IRs.shocks(%d).entries(%d).first_order', i, j));
        validate_irf_matrix(shock_entry.second_order, R.N_ROWS, logical(run_flags.has_2ndorder), ...
            context, sprintf('ModelData_IRs.shocks(%d).entries(%d).second_order', i, j));
        validate_irf_matrix(shock_entry.perfect_foresight, R.N_ROWS, logical(run_flags.has_pf), ...
            context, sprintf('ModelData_IRs.shocks(%d).entries(%d).perfect_foresight', i, j));
    end
end
end

function assert_required_fields(s, required_fields, context, struct_name)
missing_fields = {};
for i = 1:numel(required_fields)
    if ~isfield(s, required_fields{i})
        missing_fields{end+1} = required_fields{i}; %#ok<AGROW>
    end
end

if ~isempty(missing_fields)
    error('validate_ModelData_IRs:MissingFields', ...
        '[%s] %s is missing required fields: %s', ...
        context, struct_name, strjoin(missing_fields, ', '));
end
end

function validate_irf_matrix(value, expected_rows, is_required, context, value_name)
if isempty(value)
    assert(isnumeric(value), ...
        'validate_ModelData_IRs:InvalidIRFMatrix', ...
        '[%s] %s must be a numeric matrix or an empty numeric array.', ...
        context, value_name);
    assert(~is_required, ...
        'validate_ModelData_IRs:MissingIRFMatrix', ...
        '[%s] %s must be populated when its run flag is enabled.', ...
        context, value_name);
    return;
end

assert(isnumeric(value) && ismatrix(value) && ...
    size(value, 1) == expected_rows && size(value, 2) >= 1, ...
    'validate_ModelData_IRs:InvalidIRFMatrix', ...
    '[%s] %s must be a numeric matrix with %d rows and at least 1 column.', ...
    context, value_name, expected_rows);
end

function validate_summary_stats(summary_stats, n_analyzed, context, stats_name)
assert(isstruct(summary_stats) && ~isempty(fieldnames(summary_stats)), ...
    'validate_ModelData_IRs:InvalidSummaryStats', ...
    '[%s] %s must be a non-empty struct.', context, stats_name);
assert_required_fields(summary_stats, {'peaks', 'peak_periods', 'half_lives', 'amplifications'}, ...
    context, stats_name);
assert_required_fields(summary_stats.peaks, {'first_order', 'second_order', 'perfect_foresight'}, ...
    context, [stats_name '.peaks']);
assert_required_fields(summary_stats.peak_periods, {'first_order', 'second_order', 'perfect_foresight'}, ...
    context, [stats_name '.peak_periods']);
assert_required_fields(summary_stats.half_lives, {'first_order', 'second_order', 'perfect_foresight'}, ...
    context, [stats_name '.half_lives']);
assert_required_fields(summary_stats.amplifications, {'abs', 'second_order', 'rel'}, ...
    context, [stats_name '.amplifications']);

validate_summary_row(summary_stats.peaks.first_order, n_analyzed, context, [stats_name '.peaks.first_order']);
validate_summary_row(summary_stats.peaks.second_order, n_analyzed, context, [stats_name '.peaks.second_order']);
validate_summary_row(summary_stats.peaks.perfect_foresight, n_analyzed, context, [stats_name '.peaks.perfect_foresight']);
validate_summary_row(summary_stats.peak_periods.first_order, n_analyzed, context, [stats_name '.peak_periods.first_order']);
validate_summary_row(summary_stats.peak_periods.second_order, n_analyzed, context, [stats_name '.peak_periods.second_order']);
validate_summary_row(summary_stats.peak_periods.perfect_foresight, n_analyzed, context, [stats_name '.peak_periods.perfect_foresight']);
validate_summary_row(summary_stats.half_lives.first_order, n_analyzed, context, [stats_name '.half_lives.first_order']);
validate_summary_row(summary_stats.half_lives.second_order, n_analyzed, context, [stats_name '.half_lives.second_order']);
validate_summary_row(summary_stats.half_lives.perfect_foresight, n_analyzed, context, [stats_name '.half_lives.perfect_foresight']);
validate_summary_row(summary_stats.amplifications.abs, n_analyzed, context, [stats_name '.amplifications.abs']);
validate_summary_row(summary_stats.amplifications.second_order, n_analyzed, context, [stats_name '.amplifications.second_order']);
validate_summary_row(summary_stats.amplifications.rel, n_analyzed, context, [stats_name '.amplifications.rel']);
end

function validate_summary_row(value, n_analyzed, context, value_name)
assert(isnumeric(value) && isvector(value) && numel(value) == n_analyzed, ...
    'validate_ModelData_IRs:InvalidSummaryRow', ...
    '[%s] %s must be a numeric vector of length %d.', context, value_name, n_analyzed);
end
