function validate_ModelData(ModelData, context)
% VALIDATE_MODELDATA Validate the lightweight saved model artifact

if nargin < 2
    context = 'validate_ModelData';
end

assert(isstruct(ModelData) && ~isempty(fieldnames(ModelData)), ...
    'validate_ModelData:InvalidArtifact', '[%s] ModelData must be a non-empty struct.', context);

required_top = {'metadata', 'calibration', 'params', 'EmpiricalTargets', 'SteadyState'};
assert_required_fields(ModelData, required_top, context, 'ModelData');

metadata_fields = {'date', 'exp_label', 'save_label', 'model_type', ...
    'sector_indices', 'config', 'exp_paths', 'n_shocks', ...
    'run_flags', 'has_irfs', 'has_diagnostics'};
assert_required_fields(ModelData.metadata, metadata_fields, context, 'ModelData.metadata');

steady_state_fields = {'parameters', 'policies_ss', 'endostates_ss', 'C_ss', ...
    'L_ss', 'GDP_ss', 'I_ss', 'K_ss', 'utility_intratemp_ss'};
assert_required_fields(ModelData.SteadyState, steady_state_fields, context, 'ModelData.SteadyState');

assert(isstruct(ModelData.metadata.run_flags), ...
    'validate_ModelData:MissingRunFlags', '[%s] ModelData.metadata.run_flags must be a struct.', context);
assert_required_fields(ModelData.metadata.run_flags, ...
    {'has_1storder', 'has_2ndorder', 'has_pf', 'has_mit'}, context, 'ModelData.metadata.run_flags');

assert(isnumeric(ModelData.metadata.n_shocks) && isscalar(ModelData.metadata.n_shocks) && ...
    ModelData.metadata.n_shocks >= 0 && ModelData.metadata.n_shocks == floor(ModelData.metadata.n_shocks), ...
    'validate_ModelData:InvalidShockCount', ...
    '[%s] ModelData.metadata.n_shocks must be a non-negative integer scalar.', context);

sector_indices = ModelData.metadata.sector_indices(:);
assert(isnumeric(sector_indices) && ~isempty(sector_indices), ...
    'validate_ModelData:InvalidSectorIndices', ...
    '[%s] ModelData.metadata.sector_indices must be a non-empty numeric vector.', context);

assert(isfield(ModelData.metadata.config, 'sector_indices') && ...
    isequal(ModelData.metadata.config.sector_indices(:), sector_indices), ...
    'validate_ModelData:ConfigSectorMismatch', ...
    '[%s] Config sector indices do not match ModelData.metadata.sector_indices.', context);

if isfield(ModelData.metadata.config, 'shock_values')
    assert(numel(ModelData.metadata.config.shock_values) == ModelData.metadata.n_shocks, ...
        'validate_ModelData:ShockCountMismatch', ...
        '[%s] metadata.n_shocks must match numel(metadata.config.shock_values).', context);
end

assert(isfield(ModelData.params, 'n_sectors') && isnumeric(ModelData.params.n_sectors) && ...
    isscalar(ModelData.params.n_sectors) && ModelData.params.n_sectors >= max(sector_indices), ...
    'validate_ModelData:InvalidSectorCount', ...
    '[%s] ModelData.params.n_sectors must be a scalar covering all analyzed sectors.', context);

n_sectors = ModelData.params.n_sectors;
idx = get_variable_indices(n_sectors);
assert_numeric_vector_length(ModelData.SteadyState.endostates_ss, n_sectors, ...
    'ModelData.SteadyState.endostates_ss', context);
assert_numeric_vector_length(ModelData.SteadyState.policies_ss, idx.n_policies, ...
    'ModelData.SteadyState.policies_ss', context);

if isfield(ModelData, 'Statistics')
    validate_statistics_block(ModelData.Statistics, idx, context);
end
validate_theoretical_stats(ModelData, context);

if ModelData.metadata.has_diagnostics
    assert(isfield(ModelData, 'Diagnostics') && isstruct(ModelData.Diagnostics) && ...
        ~isempty(fieldnames(ModelData.Diagnostics)), ...
        'validate_ModelData:MissingDiagnostics', ...
        '[%s] ModelData.Diagnostics must be populated when has_diagnostics=true.', context);
end
end

function assert_required_fields(s, required_fields, context, struct_name)
missing_fields = {};
for i = 1:numel(required_fields)
    if ~isfield(s, required_fields{i})
        missing_fields{end+1} = required_fields{i}; %#ok<AGROW>
    end
end

if ~isempty(missing_fields)
    error('validate_ModelData:MissingFields', ...
        '[%s] %s is missing required fields: %s', ...
        context, struct_name, strjoin(missing_fields, ', '));
end
end

function assert_numeric_vector_length(value, expected_length, value_name, context)
assert(isnumeric(value) && isvector(value) && numel(value) == expected_length, ...
    'validate_ModelData:InvalidVectorSize', ...
    '[%s] %s must be a numeric vector of length %d.', ...
    context, value_name, expected_length);
end

function validate_statistics_block(Statistics, idx, context)
if isfield(Statistics, 'shocks_sd')
    assert(isnumeric(Statistics.shocks_sd) && isvector(Statistics.shocks_sd) && ...
        numel(Statistics.shocks_sd) == idx.n, ...
        'validate_ModelData:InvalidShockStd', ...
        '[%s] Statistics.shocks_sd must be a numeric vector of length n_sectors.', context);
end

if isfield(Statistics, 'states_sd')
    assert(isnumeric(Statistics.states_sd) && isvector(Statistics.states_sd) && ...
        numel(Statistics.states_sd) == idx.n_states, ...
        'validate_ModelData:InvalidStateStd', ...
        '[%s] Statistics.states_sd must have length n_states.', context);
end

if isfield(Statistics, 'policies_sd')
    assert(isnumeric(Statistics.policies_sd) && isvector(Statistics.policies_sd) && ...
        numel(Statistics.policies_sd) == idx.n_policies, ...
        'validate_ModelData:InvalidPolicyStd', ...
        '[%s] Statistics.policies_sd must have length n_policies.', context);
end
end

function validate_theoretical_stats(ModelData, context)
assert(isfield(ModelData, 'Statistics') && isstruct(ModelData.Statistics), ...
    'validate_ModelData:MissingStatistics', ...
    '[%s] ModelData.Statistics must exist and be a struct.', context);
assert(isfield(ModelData.Statistics, 'TheoStats') && isstruct(ModelData.Statistics.TheoStats), ...
    'validate_ModelData:MissingTheoStats', ...
    '[%s] ModelData.Statistics.TheoStats must exist and be a struct.', context);

theo = ModelData.Statistics.TheoStats;
assert(isfield(theo, 'aggregate_moments') && isstruct(theo.aggregate_moments), ...
    'validate_ModelData:MissingTheoAggregateMoments', ...
    '[%s] ModelData.Statistics.TheoStats.aggregate_moments must exist and be a struct.', context);

required_aggregates = {'C', 'L', 'GDP', 'I', 'K', 'utility_intratemp'};
for i = 1:numel(required_aggregates)
    agg_name = required_aggregates{i};
    assert(isfield(theo.aggregate_moments, agg_name) && isstruct(theo.aggregate_moments.(agg_name)), ...
        'validate_ModelData:MissingTheoAggregate', ...
        '[%s] TheoStats.aggregate_moments.%s must exist and be a struct.', context, agg_name);
end
end
