function mod_path = generate_mit_rolling_pf_mod(dynare_folder, lookahead_horizon, solver_tolf)
% generate_mit_rolling_pf_mod  Generate the .mod file for rolling MIT PF solves.
%
%   mod_path = generate_mit_rolling_pf_mod(dynare_folder, lookahead_horizon)
%   mod_path = generate_mit_rolling_pf_mod(dynare_folder, lookahead_horizon, solver_tolf)
%
%   This creates a fixed-horizon deterministic perfect-foresight problem
%   that takes the current predetermined state from workspace vectors
%   `a_init` and `k_init`, then solves forward with a zero exogenous path
%   `shockssim_mit_pf`.
%
%   Inputs:
%     dynare_folder       - path to the dynare/ folder
%     lookahead_horizon   - number of simulated periods returned by Dynare
%     solver_tolf         - nonlinear solver tolerance passed to Dynare
%
%   Output:
%     mod_path            - full path to the generated .mod file

if nargin < 3 || isempty(solver_tolf)
    solver_tolf = 1e-3;
end

if ~(isnumeric(lookahead_horizon) && isscalar(lookahead_horizon) && ...
        isfinite(lookahead_horizon) && lookahead_horizon == floor(lookahead_horizon) && ...
        lookahead_horizon >= 3)
    error('generate_mit_rolling_pf_mod:InvalidHorizon', ...
        'lookahead_horizon must be an integer scalar >= 3.');
end

simul_periods = lookahead_horizon - 2;

mod_path = fullfile(dynare_folder, 'mit_rolling_pf_generated.mod');
fid = fopen(mod_path, 'w');

fprintf(fid, '// Auto-generated rolling MIT perfect foresight file\n');
fprintf(fid, '// Generated by generate_mit_rolling_pf_mod.m - do not edit manually\n');
fprintf(fid, '// lookahead horizon = %d, solver periods = %d\n\n', ...
    lookahead_horizon, simul_periods);
fprintf(fid, '@#include "model_config.mod"\n');
fprintf(fid, '@#include "base_model_include.mod"\n\n');

write_val_block(fid, 'initval', 'n_sectors', 'a_init(@{j},1)', 'k_init(@{j},1)');

fprintf(fid, 'perfect_foresight_setup(periods=%d);\n', simul_periods);
fprintf(fid, 'oo_.exo_simul = shockssim_mit_pf;\n');
fprintf(fid, 'perfect_foresight_solver(endogenous_terminal_period, tolf=%.16g);\n', solver_tolf);

fclose(fid);

end
