function mod_path = generate_determ_simul_mod(dynare_folder, simul_periods)
% generate_determ_simul_mod  Generate the .mod file for PF stochastic simulation.
%
%   mod_path = generate_determ_simul_mod(dynare_folder, simul_periods)
%
%   Dynare requires literal integers for the periods= option. This function
%   generates a .mod file with the value hardcoded.
%
%   Inputs:
%     dynare_folder  - path to the dynare/ folder (where .mod files live)
%     simul_periods  - number of interior decision periods (= T_total - 2)
%
%   Output:
%     mod_path       - full path to the generated .mod file

mod_path = fullfile(dynare_folder, 'determ_simul_generated.mod');
fid = fopen(mod_path, 'w');

fprintf(fid, '// Auto-generated deterministic simulation file\n');
fprintf(fid, '// Generated by generate_determ_simul_mod.m — do not edit manually\n');
fprintf(fid, '// periods = %d (T_total - 2), output will have %d columns\n\n', simul_periods, simul_periods + 2);
fprintf(fid, '@#include "model_config.mod"\n');
fprintf(fid, '@#include "base_model_include.mod"\n\n');

write_val_block(fid, 'initval', 'n_sectors');
write_val_block(fid, 'endval', 'n_sectors');

fprintf(fid, 'perfect_foresight_setup(periods=%d);\n', simul_periods);
fprintf(fid, 'oo_.exo_simul = shockssim_determ;\n');
fprintf(fid, 'perfect_foresight_solver(endogenous_terminal_period, tolf=1e-3);\n');

fclose(fid);

end
