function mod_path = generate_determ_irs_mod(dynare_folder, ir_simul_periods)
% generate_determ_irs_mod  Generate the .mod file for PF impulse responses.
%
%   mod_path = generate_determ_irs_mod(dynare_folder, ir_simul_periods)
%
%   Dynare requires literal integers for the periods= option. This function
%   generates a .mod file with the value hardcoded.
%
%   The initial condition sets a_j = shocksim_0(j,1) (the TFP shock),
%   while all other variables start at steady state. No endval block is
%   needed because endogenous_terminal_period handles the terminal condition.
%
%   Inputs:
%     dynare_folder    - path to the dynare/ folder (where .mod files live)
%     ir_simul_periods - number of interior decision periods (= ir_horizon - 2)
%
%   Output:
%     mod_path         - full path to the generated .mod file

mod_path = fullfile(dynare_folder, 'determ_irs_generated.mod');
fid = fopen(mod_path, 'w');

fprintf(fid, '// Auto-generated perfect foresight IRF file\n');
fprintf(fid, '// Generated by generate_determ_irs_mod.m — do not edit manually\n');
fprintf(fid, '// periods = %d (ir_horizon - 2), output will have %d columns\n\n', ir_simul_periods, ir_simul_periods + 2);
fprintf(fid, '@#include "model_config.mod"\n');
fprintf(fid, '@#include "base_model_include.mod"\n\n');

write_val_block(fid, 'initval', 'n_sectors', 'shocksim_0(@{j},1)');

fprintf(fid, 'perfect_foresight_setup(periods=%d);\n', ir_simul_periods);
fprintf(fid, 'oo_.exo_simul = shockssim_ir;\n');
fprintf(fid, 'perfect_foresight_solver(endogenous_terminal_period, tolf=1e-3);\n');

fclose(fid);

end
