function mod_path = generate_mit_shocks_mod(dynare_folder, T_mit, burn_out_mit, n_sectors, shockssim_mit)
% generate_mit_shocks_mod  Generate the .mod file for MIT shocks simulation.
%
%   mod_path = generate_mit_shocks_mod(dynare_folder, T_mit, burn_out_mit, n_sectors, shockssim_mit)
%
%   Dynare requires literal integers for the learnt_in= and periods= options
%   in perfect_foresight_with_expectation_errors commands, and literal
%   numeric values in the values= field (workspace variables are not
%   evaluated at parse time). This function generates a .mod file with all
%   values hardcoded. Both the period (t) and sector (j) loops are fully
%   unrolled in MATLAB so that no Dynare @#for macros appear inside
%   shocks(...) blocks.
%
%   Inputs:
%     dynare_folder  - path to the dynare/ folder (where .mod files live)
%     T_mit          - number of active periods with shocks
%     burn_out_mit   - number of burn-out periods (no shocks) after active
%     n_sectors      - number of sectors
%     shockssim_mit  - T_mit x n_sectors matrix of shock values
%
%   Output:
%     mod_path       - full path to the generated .mod file

T_total_mit = T_mit + burn_out_mit;

% Generate mit_shocks_simul_generated.mod
mod_path = fullfile(dynare_folder, 'mit_shocks_simul_generated.mod');
fid = fopen(mod_path, 'w');

% Header
fprintf(fid, '// Auto-generated MIT shocks simulation file\n');
fprintf(fid, '// Generated by generate_mit_shocks_mod.m — do not edit manually\n');
fprintf(fid, '// T_mit = %d active periods + %d burn-out = %d total\n\n', T_mit, burn_out_mit, T_total_mit);
fprintf(fid, '@#include "model_config.mod"\n');
fprintf(fid, '@#include "base_model_include.mod"\n\n');

% initval block (sector loop handled by Dynare macro)
write_val_block(fid, 'initval', 'n_sectors');

% Shock blocks: MUST come before perfect_foresight_with_expectation_errors_setup,
% because the setup command extracts the contents of these blocks.
% No endval block needed: the setup command assumes terminal condition is steady state
% and recomputes it automatically.
% Both t and j loops are unrolled in MATLAB — Dynare @#for macros are not
% processed correctly inside shocks(learnt_in=...) blocks.
for t = 1:T_mit
    fprintf(fid, 'shocks(learnt_in=%d);\n', t);
    for j = 1:n_sectors
        fprintf(fid, '  var e_%d; periods %d; values %.16g;\n', j, t, shockssim_mit(t, j));
    end
    fprintf(fid, 'end;\n\n');
end

% Setup and solver (setup extracts shocks declared above)
fprintf(fid, 'perfect_foresight_with_expectation_errors_setup(periods=%d);\n\n', T_total_mit);
fprintf(fid, 'perfect_foresight_with_expectation_errors_solver;\n');
fclose(fid);

end
