// Auto-generated rolling MIT perfect foresight file
// Generated by generate_mit_rolling_pf_mod.m - do not edit manually
// lookahead horizon = 153, solver periods = 151

@#include "model_config.mod"
@#include "base_model_include.mod"

initval;
@#for j in 1:n_sectors
    e_@{j}=0;
    a_@{j}=a_init(@{j},1);
    k_@{j}=k_init(@{j},1);
    c_@{j}=policies_ss(@{j});
    l_@{j}=policies_ss(parn_sectors+@{j});
    pk_@{j}=policies_ss(2*parn_sectors+@{j});
    pm_@{j}=policies_ss(3*parn_sectors+@{j});
    m_@{j}=policies_ss(4*parn_sectors+@{j});
    mout_@{j}=policies_ss(5*parn_sectors+@{j});
    i_@{j}=policies_ss(6*parn_sectors+@{j});
    iout_@{j}=policies_ss(7*parn_sectors+@{j});
    p_@{j}=policies_ss(8*parn_sectors+@{j});
    q_@{j}=policies_ss(9*parn_sectors+@{j});
    y_@{j}=policies_ss(10*parn_sectors+@{j});
@#endfor
c_util = policies_ss(11*parn_sectors+1);
l_util = policies_ss(11*parn_sectors+2);
c_agg = policies_ss(11*parn_sectors+3);
l_agg = policies_ss(11*parn_sectors+4);
gdp_agg = policies_ss(11*parn_sectors+5);
i_agg = policies_ss(11*parn_sectors+6);
k_agg = policies_ss(11*parn_sectors+7);
utility_intratemp = policies_ss(11*parn_sectors+8);
end;

perfect_foresight_setup(periods=151);
oo_.exo_simul = shockssim_mit_pf;
perfect_foresight_solver(endogenous_terminal_period, tolf=0.001);
